title: Akash Chawan
#description: text below image
#show_downloads: true

# Add contact details
email: akashchawan985@gmail.com
linkedin: https://www.linkedin.com/in/your-profile
github: https://github.com/your-username


theme: jekyll-theme-minimal
